export default [{
  "id": 1,
  "name": "班费",
  "date": "2019-04-06",
  "amount": 3400,
  "type": 1,
  "details": {
    "total": 3400,
    "number": 34,
    "price": 100
  }
}, {
  "id": 2,
  "name": "班服",
  "date": "2019-09-20",
  "amount": 1870,
  "type": 2,
  "details": {
    "total": 1870,
    "items": [{
      "name": "班服",
      "number": 34,
      "price": 55
    }]
  }
}, {
  "id": 3,
  "name": "集章小礼物",
  "date": "2019-11-13",
  "amount": 257.3,
  "type": 2,
  "details": {
    "total": 257.3,
    "items": [{
      "name": "多肉营养土",
      "number": 1,
      "price": 6.2
    }, {
      "name": "育苗盆",
      "number": 1,
      "price": 25.8
    }, {
      "name": "种植盆",
      "number": 2,
      "price": 6.62
    }, {
      "name": "一次性纸盘刀叉",
      "number": 1,
      "price": 9.9
    }, {
      "name": "木头片",
      "number": 1,
      "price": 26.28
    }, {
      "name": "海绵球",
      "number": 1,
      "price": 27.86
    }, {
      "name": "量杯",
      "number": 4,
      "price": 4.7
    }, {
      "name": "乒乓球",
      "number": 1,
      "price": 14.5
    }, {
      "name": "手工折纸",
      "number": 1,
      "price": 34
    }, {
      "name": "文具",
      "number": 1,
      "price": 50.9
    }, {
      "name": "铅笔",
      "number": 2,
      "price": 14.9
    }]
  }
}];
